import { ethers } from "hardhat";

import { toHashMap } from "./utils";

export const HypercertMinter_V0 = "HypercertMinterV0";
export const HypercertMinter_V1 = "HypercertMinterV1";

export const HypercertMinter_Upgrade = "HypercertMinterUpgrade";

export const UPGRADER_ROLE = ethers.utils.id("UPGRADER_ROLE");

export const Rights = toHashMap(["admin", "mint", "merge", "split", "burn"]);
export const ImpactScopes = toHashMap(["clean-air", "biodiversity", "pollution-reduction", "top-soil-growth"]);
export const WorkScopes = toHashMap(["clean-air-tech", "education", "tree-planting", "waterway-cleaning"]);
export const LoremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor aliquam nulla facilisi cras. Libero volutpat sed cras ornare. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Malesuada fames ac turpis egestas. In vitae turpis massa sed elementum tempus egestas sed. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Diam in arcu cursus euismod quis viverra nibh cras. Condimentum vitae sapien pellentesque habitant. Eu lobortis elementum nibh tellus molestie nunc. Lorem ipsum dolor sit amet consectetur adipiscing. Netus et malesuada fames ac turpis. Ornare quam viverra orci sagittis eu. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Tempor commodo ullamcorper a lacus vestibulum sed. Arcu ac tortor dignissim convallis aenean et. Et ultrices neque ornare aenean euismod. In arcu cursus euismod quis viverra nibh cras pulvinar.

Egestas congue quisque egestas diam in arcu cursus euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada. Fermentum posuere urna nec tincidunt praesent semper. Habitant morbi tristique senectus et netus et malesuada fames ac. Velit sed ullamcorper morbi tincidunt. Vulputate mi sit amet mauris commodo quis. Lorem ipsum dolor sit amet consectetur adipiscing elit. Varius quam quisque id diam vel. Euismod quis viverra nibh cras pulvinar mattis nunc sed. In vitae turpis massa sed elementum tempus egestas sed. Nam at lectus urna duis convallis convallis tellus. Consectetur a erat nam at lectus urna.

Egestas purus viverra accumsan in. Neque aliquam vestibulum morbi blandit cursus. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Dolor morbi non arcu risus quis. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Magna ac placerat vestibulum lectus mauris ultrices eros in. Pellentesque dignissim enim sit amet venenatis urna cursus. Senectus et netus et malesuada fames ac. Cras sed felis eget velit aliquet sagittis id consectetur. Ut lectus arcu bibendum at varius. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Ultrices eros in cursus turpis massa. Id velit ut tortor pretium viverra suspendisse potenti. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac.

Orci nulla pellentesque dignissim enim. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Justo eget magna fermentum iaculis eu. Felis eget nunc lobortis mattis. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Ultrices tincidunt arcu non sodales. Cras pulvinar mattis nunc sed blandit libero volutpat. Quis eleifend quam adipiscing vitae.

Amet nisl suscipit adipiscing bibendum est ultricies. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Neque vitae tempus quam pellentesque nec nam aliquam sem. Id semper risus in hendrerit gravida. Accumsan tortor posuere ac ut consequat. Eget gravida cum sociis natoque penatibus. Egestas integer eget aliquet nibh praesent. Nunc sed blandit libero volutpat sed cras. Amet nisl suscipit adipiscing bibendum est. Vehicula ipsum a arcu cursus vitae congue mauris. Ut ornare lectus sit amet est placerat. Dignissim suspendisse in est ante in. Leo vel orci porta non pulvinar neque. Consectetur lorem donec massa sapien faucibus et. Faucibus purus in massa tempor nec feugiat nisl pretium fusce.

Pretium aenean pharetra magna ac. Suspendisse sed nisi lacus sed viverra tellus in. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Commodo quis imperdiet massa tincidunt. Facilisi cras fermentum odio eu feugiat. Non diam phasellus vestibulum lorem sed. Imperdiet massa tincidunt nunc pulvinar. Turpis massa sed elementum tempus egestas sed. Bibendum enim facilisis gravida neque convallis a cras semper.

Est velit egestas dui id ornare arcu odio ut sem. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Massa placerat duis ultricies lacus. Sociis natoque penatibus et magnis dis. Quis risus sed vulputate odio ut enim blandit volutpat. Turpis nunc eget lorem dolor sed viverra. Magna eget est lorem ipsum dolor sit amet. Maecenas ultricies mi eget mauris. Duis at tellus at urna condimentum.

Neque egestas congue quisque egestas diam in arcu cursus euismod. Nullam non nisi est sit amet facilisis magna etiam. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Consequat mauris nunc congue nisi vitae suscipit tellus mauris. Eu lobortis elementum nibh tellus molestie nunc non blandit. Morbi tristique senectus et netus et malesuada fames. Euismod quis viverra nibh cras pulvinar mattis nunc. Tellus at urna condimentum mattis pellentesque id. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Urna neque viverra justo nec ultrices. Pellentesque elit ullamcorper dignissim cras tincidunt. Et netus et malesuada fames ac turpis egestas integer eget. Pharetra massa massa ultricies mi quis hendrerit dolor. Ut porttitor leo a diam sollicitudin tempor. Diam in arcu cursus euismod quis viverra nibh cras. At lectus urna duis convallis convallis. Ipsum dolor sit amet consectetur. Suspendisse in est ante in nibh. Pellentesque nec nam aliquam sem.

Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Ac tincidunt vitae semper quis lectus. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Ipsum a arcu cursus vitae congue. Massa sed elementum tempus egestas sed sed. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Adipiscing bibendum est ultricies integer quis. Ornare quam viverra orci sagittis eu volutpat. Fermentum odio eu feugiat pretium nibh ipsum consequat. Venenatis lectus magna fringilla urna porttitor. Maecenas sed enim ut sem viverra aliquet. Aenean vel elit scelerisque mauris pellentesque. Nibh tellus molestie nunc non blandit. Odio tempor orci dapibus ultrices.

Eros donec ac odio tempor. Cras adipiscing enim eu turpis egestas pretium aenean. Turpis egestas sed tempus urna et. Sit amet venenatis urna cursus eget nunc. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Nec dui nunc mattis enim ut tellus elementum sagittis. Odio eu feugiat pretium nibh ipsum consequat. Maecenas volutpat blandit aliquam etiam erat velit. Eu non diam phasellus vestibulum lorem sed. Volutpat sed cras ornare arcu dui. Sagittis eu volutpat odio facilisis mauris. Nibh cras pulvinar mattis nunc. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Integer vitae justo eget magna fermentum. Urna cursus eget nunc scelerisque viverra mauris in.

Bibendum at varius vel pharetra vel turpis nunc eget lorem. Porttitor eget dolor morbi non arcu risus quis. Augue ut lectus arcu bibendum at. Et malesuada fames ac turpis egestas sed tempus urna et. Vivamus at augue eget arcu dictum varius duis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Enim praesent elementum facilisis leo. Augue ut lectus arcu bibendum at varius vel pharetra vel. Gravida cum sociis natoque penatibus et magnis. Id aliquet lectus proin nibh nisl condimentum. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Pharetra diam sit amet nisl. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. At varius vel pharetra vel turpis. Ornare arcu odio ut sem nulla.

Duis at consectetur lorem donec massa sapien faucibus et molestie. Pharetra convallis posuere morbi leo urna molestie at elementum eu. Lacus vestibulum sed arcu non. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Sed elementum tempus egestas sed sed risus pretium quam. Felis donec et odio pellentesque diam. Ultrices sagittis orci a scelerisque. Urna nunc id cursus metus aliquam eleifend mi in nulla. Sed odio morbi quis commodo odio aenean. Ipsum nunc aliquet bibendum enim facilisis. Ac tincidunt vitae semper quis lectus nulla at. Massa tempor nec feugiat nisl pretium fusce id.

Integer vitae justo eget magna fermentum iaculis. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Nullam eget felis eget nunc lobortis mattis aliquam. A lacus vestibulum sed arcu non odio euismod. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Sit amet est placerat in egestas erat. Lacinia at quis risus sed vulputate odio ut. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Purus gravida quis blandit turpis cursus. Facilisi nullam vehicula ipsum a arcu cursus. Vel facilisis volutpat est velit egestas dui id. Vel pretium lectus quam id leo in vitae turpis massa. In iaculis nunc sed augue. Nunc vel risus commodo viverra maecenas accumsan lacus.

Amet consectetur adipiscing elit pellentesque habitant morbi. Sit amet mattis vulputate enim nulla. Sit amet nisl suscipit adipiscing bibendum est ultricies. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Blandit aliquam etiam erat velit. Gravida cum sociis natoque penatibus et magnis. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Augue neque gravida in fermentum et sollicitudin ac orci. Eget magna fermentum iaculis eu non. Libero id faucibus nisl tincidunt eget nullam. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Id neque aliquam vestibulum morbi blandit cursus. Purus sit amet volutpat consequat. Auctor augue mauris augue neque gravida. Cras pulvinar mattis nunc sed blandit libero. Libero enim sed faucibus turpis in eu mi. Pharetra sit amet aliquam id diam maecenas ultricies mi eget.

Sed libero enim sed faucibus. Neque sodales ut etiam sit amet nisl. Sit amet nulla facilisi morbi tempus iaculis. Sed ullamcorper morbi tincidunt ornare. Nibh tellus molestie nunc non blandit massa enim nec dui. Aliquet enim tortor at auctor urna nunc id. Augue neque gravida in fermentum et sollicitudin. Et ligula ullamcorper malesuada proin libero nunc consequat. Amet tellus cras adipiscing enim eu turpis egestas pretium. Mauris a diam maecenas sed enim ut sem viverra aliquet. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus.

Faucibus ornare suspendisse sed nisi lacus sed. Ac ut consequat semper viverra nam libero justo laoreet. Posuere morbi leo urna molestie at elementum. Viverra aliquet eget sit amet tellus cras adipiscing. Ullamcorper eget nulla facilisi etiam dignissim diam. Augue interdum velit euismod in pellentesque massa placerat duis. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Sed vulputate mi sit amet mauris commodo quis. Ut pharetra sit amet aliquam id diam maecenas ultricies. Eget mauris pharetra et ultrices. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Et netus et malesuada fames ac turpis. Dui id ornare arcu odio ut sem nulla. A diam sollicitudin tempor id eu. Magna fermentum iaculis eu non diam phasellus. Accumsan tortor posuere ac ut.

Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Cras ornare arcu dui vivamus arcu felis bibendum ut. Accumsan sit amet nulla facilisi. Quisque egestas diam in arcu cursus euismod quis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Proin sed libero enim sed faucibus turpis. Sed turpis tincidunt id aliquet risus feugiat in. Faucibus pulvinar elementum integer enim neque volutpat. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. In egestas erat imperdiet sed. Aliquet lectus proin nibh nisl condimentum. Imperdiet sed euismod nisi porta lorem mollis aliquam ut.

Nisi quis eleifend quam adipiscing vitae proin. Sollicitudin tempor id eu nisl nunc mi. Vitae et leo duis ut diam. Quis imperdiet massa tincidunt nunc pulvinar sapien. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Purus sit amet luctus venenatis lectus magna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Dictum varius duis at consectetur lorem donec massa sapien. Nulla pellentesque dignissim enim sit amet venenatis. Odio facilisis mauris sit amet. At in tellus integer feugiat scelerisque varius morbi enim nunc. Consectetur a erat nam at lectus urna duis. Amet luctus venenatis lectus magna fringilla. Varius vel pharetra vel turpis nunc. Amet porttitor eget dolor morbi non arcu risus.

Morbi tempus iaculis urna id volutpat lacus laoreet. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Ut etiam sit amet nisl purus in mollis. Porttitor rhoncus dolor purus non enim praesent elementum. Lorem ipsum dolor sit amet consectetur. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Purus semper eget duis at tellus. In fermentum posuere urna nec. Porttitor lacus luctus accumsan tortor posuere ac ut. Integer feugiat scelerisque varius morbi. Mi sit amet mauris commodo quis. Pharetra convallis posuere morbi leo urna molestie at. Dictum non consectetur a erat nam at. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Et ultrices neque ornare aenean. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Nulla pellentesque dignissim enim sit amet venenatis. Ullamcorper dignissim cras tincidunt lobortis feugiat.

In pellentesque massa placerat duis ultricies lacus sed. Sit amet venenatis urna cursus eget nunc. Commodo elit at imperdiet dui accumsan sit amet. Sed euismod nisi porta lorem mollis aliquam ut. Amet est placerat in egestas erat imperdiet sed euismod nisi. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Turpis egestas integer eget aliquet nibh praesent tristique. Sed pulvinar proin gravida hendrerit lectus a. Risus viverra adipiscing at in tellus integer. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Quis ipsum suspendisse ultrices gravida. Aliquet bibendum enim facilisis gravida neque convallis a. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Bibendum ut tristique et egestas quis ipsum suspendisse. Aliquet nibh praesent tristique magna sit amet purus.

Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Aliquet bibendum enim facilisis gravida. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Arcu cursus vitae congue mauris rhoncus aenean vel. Ut tristique et egestas quis ipsum. Amet dictum sit amet justo donec. Nisl tincidunt eget nullam non nisi est. Fermentum odio eu feugiat pretium nibh ipsum consequat. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Eget nullam non nisi est sit amet facilisis. Viverra vitae congue eu consequat ac. In hendrerit gravida rutrum quisque non. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur.

Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Purus faucibus ornare suspendisse sed nisi lacus sed. Suspendisse sed nisi lacus sed. Viverra aliquet eget sit amet tellus cras adipiscing. Egestas sed sed risus pretium quam. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Varius sit amet mattis vulputate enim. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Lacus vestibulum sed arcu non odio euismod lacinia at. Eget arcu dictum varius duis at consectetur lorem. Aliquam faucibus purus in massa tempor nec. Lacus sed turpis tincidunt id aliquet risus feugiat. Diam in arcu cursus euismod. Fringilla est ullamcorper eget nulla facilisi.

Dolor purus non enim praesent elementum. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Diam ut venenatis tellus in metus vulputate eu. Duis convallis convallis tellus id interdum velit laoreet. Ultrices gravida dictum fusce ut placerat orci. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Vel turpis nunc eget lorem dolor sed. Amet justo donec enim diam vulputate ut pharetra sit amet. Tortor condimentum lacinia quis vel. At quis risus sed vulputate odio ut enim blandit volutpat. Massa eget egestas purus viverra. Ornare quam viverra orci sagittis.

Facilisis leo vel fringilla est ullamcorper eget nulla. Bibendum est ultricies integer quis auctor elit. Et ligula ullamcorper malesuada proin libero nunc. Ornare suspendisse sed nisi lacus sed viverra tellus. Massa enim nec dui nunc. In nisl nisi scelerisque eu ultrices vitae auctor eu. Tempus urna et pharetra pharetra massa. Tincidunt ornare massa eget egestas purus. Nunc sed blandit libero volutpat sed cras. Amet consectetur adipiscing elit ut aliquam purus sit amet. Amet commodo nulla facilisi nullam. Placerat duis ultricies lacus sed turpis tincidunt id. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec.

Congue nisi vitae suscipit tellus mauris a diam. Commodo ullamcorper a lacus vestibulum sed arcu non. Elementum nibh tellus molestie nunc non blandit massa enim. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Enim nulla aliquet porttitor lacus luctus accumsan. Senectus et netus et malesuada fames ac turpis egestas maecenas. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Nulla facilisi cras fermentum odio eu feugiat. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Massa id neque aliquam vestibulum morbi blandit cursus risus at.`;
